### ISSUE TITLE
Reutilizar lo de práctica 1 con construcción automática de tests y documentación

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-ltejadal#10]

**Comment by C1587S** [comment]
Se corrigió la acción con la que se generaba de manera  autoḿatica el documento en:

https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/.github/workflows/sphinx-doc.yml

Adicionalmente, se eliminaron folders y estructura de carpetas que ya no son necesarias. 

Ahora la documentación se genera a partir de la rama gh-pages/root/ y se compila con la acción incluída.
