### ISSUE TITLE
Actualización de documentación indicando que existen imágenes de docker

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-ltejadal#11]

**Comment by C1587S** [comment]
Se completó en el commit bc645aefb16bf0ada5a594e9e934aac9fdf03f73 del repo donde se encuentra la librería [practica-1-segunda-parte](https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/commits/main).

Se incluyó el archivo [`docker_images.rst `](https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/docs/docker_images.rst)  y se ajustó el index para que lo incluya.
