### ISSUE TITLE
Robustecer código de Ant Colony

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-ltejadal#2]
- [x] Modificar el funcionamiento del algoritmo a programación orientada a objetos
- [x] Separar actualización de feromonas
- [x] Separar mecanismo para evaporación

**Comment by C1587S** [comment]
Se debe trabajar en algunas tareas específicas para robustecer la librería:
- [ ] Modificar el funcionamiento del algoritmo a programación orientada a objetos.
- [ ] Separar actualización de feromonas.
- [ ] Separar mecanismo de evaporación.
- [ ] Crear método para optimizar hiper-parámetros del algoritmo.
- [ ] Visualización: señalar el grafo de origen en el recorrido.

**Comment by C1587S** [comment]
- Se separaron los metodos de inicialización de los componentes del algoritmo y se incluyeron en https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/ant_colony/utils.py. 
Especificamente, las funciones:
    - `create_dic_dist`
    - `init_ferom`
    - `init_atrac`
    - `atraccion_nodos`
  
 - Se rediseño el algoritmo utilizando programación orientada a objetos. Se incluyeron las clases `ant` y `colony` en el siguiente _script_ : https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/ant_colony/aco_tsp_oo.py

- Los mecanismos de actualización de feromonas y de evaporación se inclueron como métodos de la clase `colony`. `_update_many_pheromone_levels` y `_evaporates_pheromone`, respectivamente.
