### ISSUE TITLE
Construcción de pipelines con kale

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-ltejadal#6]

**Comment by C1587S** [comment]
Como primer _pipeline_ en https://github.com/optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-ltejadal/tree/main/notebooks/pipelines/pipeline-matriz-aleatoria se incluyó un experimento que: 
- Crea una matriz aleatoria
- Busca los mejores hiper-parámetros
- Soluciona el propblema TSP
- Grafica, y guarda la solución encotnrada por el algoritmo en disco.
