### ISSUE TITLE
Optimización y Visualización

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-ltejadal#7]
- [x] Crear método para optimizar hiperparámetros del algoritmo
- [x] Visualización: señalar el grafo de origen en el recorrido
- [x] Crear función para estandarizar input de la clase

**Comment by C1587S** [comment]
Tarea de visualización, completada en https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/ant_colony/utils.py, en la función `graph_optim_path`.

**Comment by C1587S** [comment]
Tarea de estandarizar _input_, completada en https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/ant_colony/utils.py, en la función `read_data`.

**Comment by C1587S** [comment]
Se creó script para encotnrar los mejores hiper-parámetros del algoritmo utilizando [optuna](https://optuna.org/) en:

https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/ant_colony/optim_hyper.py

Adicionalmente, se creó un [notebook](https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/notebooks/optimizacion_hiperparametros.ipynb) para ejemplificar la utilización de las funciones agregadas.
